CREATE OR REPLACE PROCEDURE "GET_PI"()
RETURNS NUMBER(38,0)
LANGUAGE PYTHON
RUNTIME_VERSION = '3.8'
PACKAGES = ('snowflake-snowpark-python')
HANDLER = 'library.get_pi'
IMPORTS = ('@STAGE_DB.PUBLIC.MY_STAGE/library.py')
COMMENT='Surprisingly this returns pi'
EXECUTE AS OWNER
;