CREATE OR REPLACE PROCEDURE "OWNERS_RIGHTS_OUTPUT_MESSAGE"("MESSAGE" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE SQL
EXECUTE AS OWNER
AS 'BEGIN
  select area_of_circle(1);  
  RETURN message;
END';